"""Writer context builder for scene prose generation."""

from typing import Dict, Any, List, Optional
from pathlib import Path


try:
    from novel_agent.reference.indexer import ReferenceIndexer
    _HAS_REFERENCE = True
except ImportError:
    _HAS_REFERENCE = False

from novel_agent.skill.injector import build_skill_context as _build_skill_context

# 文风/写作方法注入（独立模块，失败不影响核心）
def _get_style_context(state: dict) -> str:
    try:
        from novel_agent.template.inject import get_style_context
        return get_style_context(state)
    except Exception:
        return ""

def _get_craft_context(state: dict) -> str:
    try:
        from novel_agent.template.inject import get_craft_context
        return get_craft_context(state)
    except Exception:
        return ""


class WriterContextBuilder:
    """Builds context for the scene writer LLM."""
    
    def __init__(self, memory_manager, vector_store, config):
        """Initialize writer context builder.
        
        Args:
            memory_manager: MemoryManager instance
            vector_store: VectorStore instance
            config: Configuration object
        """
        self.memory = memory_manager
        self.vector = vector_store
        self.config = config
    
    def build_writer_context(
        self,
        plan: Dict[str, Any],
        execution_results: Dict[str, Any],
        project_state: Dict[str, Any],
        eval_feedback: str = "",
        notes: str = "",
    ) -> Dict[str, Any]:
        """Build context dictionary for writer prompt.

        Args:
            plan: The plan generated by planner
            execution_results: Results from plan execution
            project_state: Current project state
            eval_feedback: Feedback from previous evaluation failure for retry
            notes: Per-tick direction notes (CLI --notes flag)
        """
        # Extract basic info
        novel_name = project_state.get("novel_name", "Untitled Novel")
        current_tick = project_state.get("current_tick", 0)
        foundation = project_state.get("story_foundation", {})
        foundation_summary = (
            f"Genre: {foundation.get('genre', '')}\n"
            f"Premise: {foundation.get('premise', '')}\n"
            f"Protagonist: {foundation.get('protagonist_archetype', '')}\n"
            f"Setting: {foundation.get('setting', '')}\n"
            f"Tone: {foundation.get('tone', '')}"
        )
        scene_intention = plan.get("scene_intention", "Continue the story")
        key_change = plan.get("key_change", "Advance the plot")
        progress_milestone = plan.get("progress_milestone", "")
        progress_step = plan.get("progress_step", "")
        pov_character_id = plan.get("pov_character", "")
        location_id = plan.get("target_location")
        scene_mode = plan.get("scene_mode", "")
        palette_shift = plan.get("palette_shift", "")
        transition_path = plan.get("transition_path", "")
        dialogue_targets = plan.get("dialogue_targets", "")
        climax_beat = plan.get("climax_beat", "")
        opening_hook = plan.get("opening_hook", "")
        pacing_notes = plan.get("pacing_notes", "")
        
        # Get POV character details
        pov_character_name, pov_character_details = self._get_character_details(
            pov_character_id
        )
        
        # Get location details
        location_name, location_details = self._get_location_details(location_id)
        
        # Format recent context
        summary_count = self.config.get('generation.summary_scenes_count', 5)
        recent_context = self._format_recent_context(summary_count=summary_count)
        
        # Format tool results
        tool_results_summary = self._format_tool_results(execution_results)
        
        # Get optional length guidance from plan metadata
        scene_length_guidance = self._get_length_guidance(plan)
        
        # Format plot beat section
        plot_beat_section = self._format_plot_beat_section(plan)

        # Thread / story goal context for Writer
        thread_context = self._format_thread_context(project_state.get("current_tick", 0))
        story_goal_context = self._format_story_goal(project_state)

        context = {
            "novel_name": novel_name,
            "current_tick": current_tick,
            "story_foundation_summary": foundation_summary,
            "scene_intention": scene_intention,
            "key_change": key_change,
            "progress_milestone": progress_milestone,
            "progress_step": progress_step,
            "plot_beat_section": plot_beat_section,
            "scene_mode": scene_mode,
            "palette_shift": palette_shift,
            "transition_path": transition_path,
            "dialogue_targets": dialogue_targets,
            "climax_beat": climax_beat,
            "opening_hook": opening_hook,
            "pacing_notes": pacing_notes,
            "eval_feedback": eval_feedback,
            "pov_character_id": pov_character_id,
            "pov_character_name": pov_character_name,
            "pov_character_details": pov_character_details,
            "location_id": location_id,
            "location_name": location_name,
            "location_details": location_details,
            "recent_context": recent_context,
            "tool_results_summary": tool_results_summary,
            "scene_length_guidance": scene_length_guidance,
            "thread_context": thread_context,
            "story_goal_context": story_goal_context,
            "skill_context": _build_skill_context(
                project_state,
                store_path=(self.config.get("skill") or {}).get("store_path"),
            ),
            "reference_context": self._search_references(plan, project_state),
            "style_context": _get_style_context(project_state),
            "craft_context": _get_craft_context(project_state),
            "world_rules": self._format_world_rules(),
            "writer_notes": self._format_writer_notes(notes),
        }

        # Token 预算裁剪（try/except 包裹，失败返回原始 context）
        try:
            from ..context.budget import ContextBudgeter
            budgeter = ContextBudgeter(self.config)
            context = budgeter.budget_writer_context(context)
        except Exception:
            pass

        return context

    def _format_writer_notes(self, per_tick_notes: str = "") -> str:
        """Format direction notes for writer context.

        Per-tick notes (CLI --notes) take precedence over config.
        Includes a continuity guard to protect character / plot coherence.
        """
        notes = per_tick_notes.strip() if per_tick_notes else self.config.get('generation.writer_notes', '')
        if not notes:
            return ''
        return (
            '\n\n## 场景方向指导（必须执行）\n\n' + notes +
            '\n\n以上是用户指定的写作方向，请严格据此撰写本章场景。'
            '在满足用户方向的前提下，保持故事连续性和角色性格一致。'
        )
    
    def _get_character_details(self, character_id: str) -> tuple[str, str]:
        """Get character name and formatted details.
        
        Args:
            character_id: Character ID
        
        Returns:
            Tuple of (character_name, formatted_details)
        """
        if not character_id:
            return "未知", "未指定 POV 角色。"

        character = self.memory.load_character(character_id)
        if not character:
            return character_id, f"角色 {character_id} 未找到。"

        details = f"**姓名：**{character.display_name}（全名：{character.full_name}）\n"
        details += f"**ID：**{character.id}\n\n"

        if character.description:
            details += f"**描述：**{character.description}\n\n"

        if character.personality and character.personality.core_traits:
            details += f"**性格：**{', '.join(character.personality.core_traits)}\n\n"

        if character.backstory:
            details += f"**背景：**{character.backstory}\n\n"

        if character.current_state.goals:
            details += f"**目标：**{', '.join(character.current_state.goals)}\n\n"

        if character.current_state.emotion and character.current_state.emotion.dominant:
            details += f"**当前情绪：**{character.current_state.emotion.dominant}"
            details += f"（效价={character.current_state.emotion.valence:.1f}）\n\n"

        return character.display_name, details.strip()
    
    def _get_location_details(self, location_id: Optional[str]) -> tuple[str, str]:
        """Get location name and formatted details.
        
        Args:
            location_id: Location ID or None
        
        Returns:
            Tuple of (location_name, formatted_details)
        """
        if not location_id:
            return "未知地点", "地点将在场景中确定。"

        location = self.memory.load_location(location_id)
        if not location:
            return location_id, f"地点 {location_id} 未找到。"

        details = f"**名称：**{location.name}\n"
        details += f"**ID：**{location.id}\n\n"

        if location.description:
            details += f"**描述：**{location.description}\n\n"

        if location.type:
            details += f"**类型：**{location.type}\n\n"
        
        if location.atmosphere:
            details += f"**Atmosphere:** {location.atmosphere}\n\n"
        
        if location.features:
            details += f"**Features:** {', '.join(location.features)}\n\n"
        
        return location.name, details.strip()
    
    def _format_recent_context(self, summary_count: int = 5) -> str:
        """Format recent context: transition tail + summaries + state snapshot.

        No full-text scenes — the writer sees structured state, not raw prose.
        """
        scene_ids = self.memory.list_scenes()
        if not scene_ids:
            return "This is the first scene of the novel."

        parts = []

        # 1. Transition tail — last ~500 chars of the previous scene
        tail = self._format_transition_tail(scene_ids)
        if tail:
            parts.append("## 上一章结尾（过渡衔接）\n")
            parts.append(tail)
            parts.append("")

        # 2. Recent summaries
        total = len(scene_ids)
        summary_start = max(0, total - summary_count)
        summary_ids = scene_ids[summary_start:total]
        if summary_ids:
            parts.append("## 近期事件\n")
            for sid in summary_ids:
                scene = self.memory.load_scene(sid)
                if scene:
                    parts.append(f"**S{scene.tick:03d} {scene.title}**")
                    if scene.summary:
                        if isinstance(scene.summary, list):
                            for bullet in scene.summary:
                                parts.append(f"- {bullet}")
                        else:
                            parts.append(scene.summary)
                    parts.append("")
            parts.append("")

        # 3. State snapshot — current state of all entities
        snapshot = self._build_state_snapshot()
        if snapshot:
            parts.append(snapshot)

        return "\n".join(parts).strip() if parts else ""

    def _format_transition_tail(self, scene_ids: list) -> str:
        """Return the last ~500 characters of the most recent scene."""
        if not scene_ids:
            return ""
        last_id = scene_ids[-1]
        scene_number = last_id[1:]  # Remove 'S' prefix
        scene_file = self.memory.project_path / "scenes" / f"scene_{scene_number}.md"
        if not scene_file.exists():
            return ""
        text = scene_file.read_text(encoding='utf-8')
        if len(text) <= 500:
            return text.strip()
        # Find a sentence boundary near the 500-char cutoff
        cut = max(0, len(text) - 500)
        for sep in ['\n\n', '。', '！', '？', '\n']:
            idx = text.rfind(sep, cut)
            if idx > cut:
                return text[idx + len(sep):].strip()
        return text[cut:].strip()

    def _build_state_snapshot(self) -> str:
        """Build a structured snapshot of the current story world state.

        Collected fresh from memory on every tick — always reflects the
        latest entity updates from the previous tick.
        """
        lines = [
            "## 故事世界当前状态（权威数据源——所有角色名、地名、势力名须以此为准）",
            "**注意：下方列表中的名称是唯一正确版本。即使近期场景文本中出现不同写法，也必须使用此处列出的名称。**",
            "",
        ]

        # --- characters ---
        char_ids = self.memory.list_characters()
        if char_ids:
            lines.append("### 角色")
            lines.append("")
            for cid in char_ids:
                c = self.memory.load_character(cid)
                if not c:
                    continue
                name = c.display_name or c.name
                role = c.role or ""
                location = c.current_state.location_id or "未知"
                physical = c.current_state.physical_state or ""
                emotion = ""
                if c.current_state.emotion and c.current_state.emotion.dominant:
                    e = c.current_state.emotion
                    emotion = f"情绪: {e.dominant} (效价{e.valence:+.1f} 唤醒{e.arousal:.1f})"
                goals = ", ".join(c.current_state.goals[:3]) if c.current_state.goals else ""

                lines.append(f"**{cid} {name}** | {role} | 位置: {location}")
                if physical:
                    lines.append(f"  身体: {physical}")
                if emotion:
                    lines.append(f"  {emotion}")
                if goals:
                    lines.append(f"  目标: {goals}")

                # relationships
                rels = self.memory.get_character_relationships(cid)
                if rels:
                    rel_parts = []
                    for r in rels[:5]:
                        other = r.get_other_character(cid)
                        oc = self.memory.load_character(other)
                        oname = oc.display_name if oc else other
                        rel_parts.append(f"{oname}({r.relationship_type}/{r.status})")
                    lines.append(f"  关系: {', '.join(rel_parts)}")
                lines.append("")
            lines.append("")

        # --- locations (recent 3) ---
        loc_ids = self.memory.list_locations()
        if loc_ids:
            lines.append("### 地点")
            lines.append("")
            recent_locs = loc_ids[-3:]
            for lid in recent_locs:
                loc = self.memory.load_location(lid)
                if not loc:
                    continue
                desc = loc.description[:120] if loc.description else ""
                lines.append(f"**{lid} {loc.name}**: {desc}")
            lines.append("")

        # --- open loops (top 8 by importance) ---
        loops = self.memory.get_open_loops()
        if loops:
            sorted_loops = sorted(loops, key=lambda x: x.importance, reverse=True)[:8]
            lines.append("### 紧迫线索")
            lines.append("")
            for loop in sorted_loops:
                status_mark = "[急]" if loop.status == "urgent" else ""
                lines.append(f"- {status_mark}**{loop.id}**: {loop.description}")
            lines.append("")

        return "\n".join(lines)

    def _format_tool_results(self, execution_results: Dict[str, Any]) -> str:
        """Format tool execution results into readable summary.
        
        Args:
            execution_results: Results from plan execution
        
        Returns:
            Formatted string summarizing tool results
        """
        if not execution_results:
            return "本场景未执行工具调用。"

        actions_executed = execution_results.get("actions_executed", [])
        if not actions_executed:
            return "本场景未执行工具调用。"

        summary_parts = []
        for action in actions_executed:
            tool_name = action.get("tool", "unknown")
            result = action.get("result", {})

            if tool_name == "memory.search":
                query = action.get("args", {}).get("query", "")
                results = result.get("results", [])
                summary_parts.append(f"- 搜索记忆'{query}'：找到 {len(results)} 条结果")

            elif tool_name == "character.generate":
                char_name = result.get("name", "Unknown")
                summary_parts.append(f"- 生成新角色：{char_name}")

            elif tool_name == "location.generate":
                loc_name = result.get("name", "Unknown")
                summary_parts.append(f"- 生成新地点：{loc_name}")

            elif tool_name == "relationship.create":
                summary_parts.append("- 创建新关系")

            elif tool_name == "relationship.update":
                summary_parts.append("- 更新关系")

            else:
                summary_parts.append(f"- 执行 {tool_name}")

        if not summary_parts:
            return "没有值得报告的工具结果。"
        
        return "\n".join(summary_parts)
    
    def _get_length_guidance(self, plan: Dict[str, Any]) -> str:
        """Get optional length guidance from plan.
        
        Args:
            plan: The plan dictionary
        
        Returns:
            Formatted length guidance string (may be empty)
        """
        # Check if plan has scene_length metadata
        metadata = plan.get("metadata", {})
        scene_length = metadata.get("scene_length", "").lower()
        
        # 数据驱动：根据长度值中的关键词判断，不硬编码具体值
        short_keywords = {"短", "brief", "short", "快速", "简"}
        long_keywords = {"长", "long", "extended", "详细", "丰富", "深入", "重", "大"}
        if any(k in scene_length for k in short_keywords):
            return "\n\n**Length Guidance:** Keep this scene brief and focused - a quick moment or transition."
        elif any(k in scene_length for k in long_keywords):
            return "\n\n**Length Guidance:** This is a major scene - write extensively, exploring all nuances and implications."

        # Fall back to config-based word count targets when no plan-level hint given
        min_words = self.config.get('generation.target_word_count_min')
        max_words = self.config.get('generation.target_word_count_max')
        if min_words and max_words:
            return (f"\n\n**Length Guidance:** Write between {min_words} and {max_words} Chinese characters. "
                    f"Do NOT stop before reaching {min_words} characters.")
        elif min_words:
            return (f"\n\n**Length Guidance:** Write at least {min_words} Chinese characters. "
                    f"Do NOT stop early — keep writing until you reach this minimum.")
        else:
            return ""
    
    def _format_plot_beat_section(self, plan: Dict[str, Any]) -> str:
        """Format plot beat section for writer prompt.

        Reads beat_target from the Planner's plan and loads the full beat
        description / constraints from plot_outline.json so the Writer knows
        exactly what story beat to execute in this scene.
        """
        beat_target = plan.get("beat_target")
        if not beat_target or not isinstance(beat_target, dict):
            return ""

        beat_id = beat_target.get("beat_id", "")
        if not beat_id:
            return ""

        # Load beat details from plot_outline.json
        try:
            from ..plot.manager import PlotOutlineManager
            manager = PlotOutlineManager(self.memory.project_path)
            outline = manager.load_outline()
            beat = next((b for b in outline.beats if b.id == beat_id), None)
        except Exception:
            beat = None

        description = getattr(beat, "description", "") if beat else ""
        if not description:
            return ""

        section = f"## 本场景必须执行的节拍\n\n"
        section += f"**{beat_id}**: {description}\n\n"

        if beat:
            chars = getattr(beat, "characters_involved", []) or []
            if chars:
                section += f"涉及角色：{', '.join(chars)}\n\n"
            loc = getattr(beat, "location", "")
            if loc:
                section += f"地点：{loc}\n\n"
            tension = getattr(beat, "tension_target", None)
            if tension is not None:
                section += f"目标张力：{tension}/10\n\n"
            threads = getattr(beat, "plot_threads", []) or []
            if threads:
                section += f"推进支线：{', '.join(threads)}\n\n"

        strategy = beat_target.get("strategy", "")
        if strategy:
            section += f"Planner 策略：{strategy}\n"
            notes = beat_target.get("notes", "")
            if notes:
                section += f"说明：{notes}\n"

        section += "\n以上节拍必须在本场景中完成。\n"
        return section

    def _search_references(self, plan: dict, project_state: dict) -> str:
        """Search reference library for relevant passages.

        Queries ReferenceIndexer using the scene intention as a search
        query and formats matching chunks as context for the Writer prompt.

        Args:
            plan: The plan dictionary with scene_intention / key_change
            project_state: Current project state dict

        Returns:
            Formatted reference context string (empty if no references or no sources configured)
        """
        reference_sources = project_state.get("reference_sources", [])
        if not reference_sources or not _HAS_REFERENCE:
            return ""

        query = plan.get("scene_intention", "") or plan.get("key_change", "")
        if not query:
            return ""

        ref_cfg = self.config.get("reference", {}) if isinstance(self.config, dict) else {}
        store_path = ref_cfg.get("store_path") if isinstance(ref_cfg, dict) else None
        top_k = ref_cfg.get("max_results", 3) if isinstance(ref_cfg, dict) else 3

        indexer = ReferenceIndexer(store_path=store_path)

        results = indexer.search(query, top_k=top_k)
        if not results:
            return ""

        sections = ["## Style References from External Novels\n"]
        for r in results:
            source = r.get("source", "Unknown")
            chapter = r.get("chapter", "")
            text = r.get("text", "")
            relevance = r.get("relevance", 0)

            header = f"**{source}**"
            if chapter:
                header += f" — {chapter}"
            header += f" (relevance: {relevance:.2f})"

            sections.append(header)
            sections.append(text)
            sections.append("")

        sections.append(
            "Apply these references as TONAL GUIDANCE only — adopt mood, pacing, "
            "and descriptive approach where fitting, but do NOT copy plot, characters, "
            "or specific phrasing."
        )

    def _format_thread_context(self, current_tick: int) -> str:
        """Active story threads for Writer awareness."""
        try:
            from ..memory.thread_manager import ThreadManager
            mgr = ThreadManager(self.memory, config=self.config)
            return mgr.format_dashboard(current_tick)
        except Exception:
            return ""

    def _format_story_goal(self, project_state: dict) -> str:
        """Story goal for Writer awareness."""
        goals = project_state.get("story_goals", {}) or {}
        primary = goals.get("primary")
        if not primary:
            return ""
        return (
            f"**故事终极目标**（第{primary.get('promoted_at_tick','?')}幕浮现）："
            f"{primary.get('description','')}\n"
        )

        return "\n".join(sections)

    def _format_world_rules(self) -> str:
        """Format world lore rules for the Writer prompt.

        Collects critical and important lore entries so the Writer is
        aware of established world constraints.
        """
        lore_entries = self.memory.load_all_lore()
        if not lore_entries:
            return ""
        # 数据驱动：按稀有度排序，条目少的重要性值=高优先级
        imp_counts: dict[str, int] = {}
        for l in lore_entries:
            imp = l.importance or "未知"
            imp_counts[imp] = imp_counts.get(imp, 0) + 1
        sorted_imps = sorted(imp_counts, key=lambda k: imp_counts[k])
        high_imps = set(sorted_imps[:max(1, len(sorted_imps)//2)])
        important = [l for l in lore_entries if (l.importance or "未知") in high_imps]
        if not important:
            important = lore_entries[:3]
        lines = ["\n## 世界观规则（请遵守）\n"]
        for l in important[:5]:
            cat = l.category or "其他"
            tag = l.lore_type or "事实"
            lines.append(f"- [{cat}·{tag}] {l.content}")
        return "\n".join(lines)
